@startuml
'https://plantuml.com/class-diagram


class Game {
    -Player* player;
    -Level* level;

    -Renderer* renderer;
    -Printer* printer;

    -IInput* input;
    -Config* config;

    -std::pair<int, int> playground_size;

    -bool saved_progress;
    -bool game_is_running;
    -int level_n;

    -void change_input();

    -void pause_menu();
    -void victory_menu();
    -void defeat_menu();
    -void settings_menu();

    -void game_loop();

    -void create_new_level();
    -void new_size();

    +Game();

    +void main_menu();

    +~Game();
}


enum menu_options{
 nothing
 play_game
 settings
 exit_game
 return_main_menu
 resume
 next_level
 new_game
 change_size
 }

class Menu {
    -std::vector<option> options;
    -int curr_option;
    -bool active;

    -void option_up();
    -void option_down();
    -menu_options choose_option() const;

    +Menu(std::vector<option> options_);
    +~Menu();

    +int get_curr_pos() const;
    +std::vector<option>& get_options();

    +menu_options update(keys key);

    +bool is_active() const;
    +void close();

}

menu_options--*Menu

class Level {
    friend Game;

    -PlayerManager* player_manager;
    -Playground* playground;
    -MapGenerator* map_generator;

    +Level(Player* player);
    +~Level();

    +void new_level(Player* player, std::pair<int, int> playground_size);
}

enum keys{
 non_key
 left_key
 right_key
 up_key
 down_key
 wait_key
 esc_key
 invalid_key
}

class Config {
    -std::map<int, keys> keymap;
    -std::vector<std::string> keys_str;

    -std::vector<int> ascii_codes_vec;
    -std::vector<keys> keys_vec;

    +Config(std::string path);
    +~Config();

    +keys pressed_key(int n);
    +bool is_valid();
}

keys--*Config
Level--*Game
Menu--*Game
Config--*Game

interface IInput{
    +virtual int scan() = 0;
    +virtual ~IInput() = default;
}

class ConsoleInput{
    +ConsoleInput();
    +~ConsoleInput();

    +int scan() final;
}

class FileInput{
    -std::fstream file;

    +FileInput(std::string path);
    +~FileInput();

    +int scan() final;
}

FileInput<|..IInput
ConsoleInput<|..IInput

IInput--*Game

left to right direction

@enduml